name: tests
on:
  push:
    branches-ignore:
      - "main"
permissions:
  actions: write
  checks: read
  contents: write
  id-token: write
  pull-requests: read
  repository-projects: read
  statuses: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make env
      - run: make test
